# Generated by Django 4.2.7 on 2024-01-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback_details',
            name='rating',
        ),
        migrations.AlterField(
            model_name='userreg',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
