# Generated by Django 4.2.7 on 2024-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_feedback_details_rating_alter_userreg_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback_details',
        ),
    ]
